version: '2'
services:
  php:
    container_name: php
    build:
      context: './docker/php7-fpm'
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./:/var/www/

  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - "6379:6379"
